Repository BoiseState/interfaith-donation, pull requests merged in 2018-03, with the labels that each got.

#157 [#156] Moved over Wiki Documentation to its own folder
  documentation/agile-artifacts/definition-of-done.md
  documentation/project-workflow-and-details/git-workflow.md
  documentation/project-workflow-and-details/project-architecture.md
  documentation/useful-resources/resources.md
Labels: documentation

#167 [#163] Added the new Need Database table along with new mock data
  docker/postgres/docker-entrypoint-initdb.d/init-user-db.sh
  docker/postgres/docker-entrypoint-initdb.d/mock-data/insert-data-sql/Alerts.sql
  docker/postgres/docker-entrypoint-initdb.d/mock-data/insert-data-sql/Callouts.sql
  docker/postgres/docker-entrypoint-initdb.d/mock-data/insert-data-sql/Donors.sql
  docker/postgres/docker-entrypoint-initdb.d/mock-data/insert-data-sql/Gifts.sql
  docker/postgres/docker-entrypoint-initdb.d/mock-data/insert-data-sql/Needs.sql
  docker/postgres/docker-entrypoint-initdb.d/mock-data/insert-data-sql/Users.sql
  docker/postgres/docker-entrypoint-initdb.d/mock-data/interfaith_DDL.sql
  docker/postgres/docker-entrypoint-initdb.d/mock-data/need.sql
Labels: back-end

#174 [#164] Created new Callout database table
  docker/postgres/docker-entrypoint-initdb.d/init-user-db.sh
  docker/postgres/docker-entrypoint-initdb.d/mock-data/callout.sql
  docker/postgres/docker-entrypoint-initdb.d/mock-data/interfaith_DDL.sql
  docker/postgres/docker-entrypoint-initdb.d/mock-data/need.sql
Labels: back-end

#181 [#169] Refactored Callout model to be based on new database schema
  donation-api/src/main/java/org/interfaithsanctuary/donationapi/model/Callout.java
Labels: back-end

#183 [#180] Created Alerts database schema and mock data
  docker/postgres/docker-entrypoint-initdb.d/init-user-db.sh
  docker/postgres/docker-entrypoint-initdb.d/mock-data/alerts.sql
  docker/postgres/docker-entrypoint-initdb.d/mock-data/interfaith_DDL.sql
  donation-api/.metadata/.plugins/org.eclipse.epp.logging.aeri.ide/org.eclipse.epp.logging.aeri.ide.server/server-config.json
Labels: back-end

#210 Branch193 cors bug
  donation-api/src/main/java/org/interfaithsanctuary/donationapi/controller/HomeController.java
  front-end-admin/.eslintrc.js
  front-end-admin/src/components/donor/DonorInfo.vue
  front-end-admin/src/components/donor/DonorList.vue
  front-end-admin/src/components/need/NeedInfo.vue
  front-end-admin/src/components/need/NeedList.vue
  front-end-admin/src/router/index.js
  front-end-admin/yarn.lock
Labels: back-end, front-end-vue

#220 Branch201 create angular service for callout json
  front-end-client/config.xml
  front-end-client/package-lock.json
  front-end-client/src/app/app.module.ts
  front-end-client/src/assets/mockData/mockCalloutNeeds.json
  front-end-client/src/pages/home/home.ts
  front-end-client/src/services/calloutService.ts
Labels: front-end-ionic, high priority

#230 [#229] Refactored Docker Compose
  docker-compose.yml
  docker/tomcat/Dockerfile
  docker/tomcat/README-tomcat-docker.md
  docker/tomcat/tomcat/run.sh
  docker/tomcat/tomcat/tomcat-users.xml
  donation-api/Dockerfile
  donation-api/pom.xml
  donation-api/src/main/java/org/interfaithsanctuary/donationapi/DonationApiApplication.java
Labels: back-end, devops
